# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6945fb159ddf2ed911677ccad2683ff22913245374e5f13ee2b8b3bf883d07c672b5edd3f9408494efc3936a17b28a765e2d060f8ac4de66ee12f5941eb0d735
  hmac_secret: df4822058632810d2d7e5111cfc99419be31a4971190c11edd37dcd13e708dcb901ec1f58df214ff937bab567c0eb0ed3b79d089908d3e20a2c79a1ca8776bef

test:
  secret_key_base: 910853a5ac4fe529453f5ffb1d1775a2d40c3108aad731b05ac22c025c4d8466c499ae2a43cecda07b69477f679ecc7710b1ce32c921df9c9ef610f1805943e6
  hmac_secret: # paste your secret here

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hmac_secret: # paste your secret here
